### ISSUE TITLE
update the team.html file 

### ISSUE THREAD

**Issue by Samarjiit** [DSCPGDAV/website#1]
there are 12 cards in the team section part. fill the card with 4 major color. eg. green,blue,red and yellow.
![ans](https://user-images.githubusercontent.com/41121431/99812802-e5650f80-2b6c-11eb-9bd6-a75310298bc3.png)

**Comment by vaibhav135** [comment]
I will do it

**Comment by Samarjiit** [comment]
issue is assigned to @vaibhav135
