### ISSUE TITLE
create a google form and link to the button named "submit your project "

### ISSUE THREAD

**Issue by Samarjiit** [DSCPGDAV/website#8]
create a form similar to this : https://docs.google.com/forms/d/e/1FAIpQLSd22Mow11_3c_ETRLDIvLXgBmYKHNadR-lo7QPpou-_S_3oRw/viewform

**Comment by djmagnusa** [comment]
> create a form similar to this : https://docs.google.com/forms/d/e/1FAIpQLSd22Mow11_3c_ETRLDIvLXgBmYKHNadR-lo7QPpou-_S_3oRw/viewform

Should I make a new form and link it to the submit button? Can you provide some details about what to include in your form

**Comment by ayushontop** [comment]
Is #7 closed?

**Comment by Samarjiit** [comment]
yup
